#ifndef __CONFIG_H__
#define __CONFIG_H__

#define THIS_DEVICE_I2C_ADDRESS 0x01

#define GATE_MOTOR_FORWARD_PIN 9
#define GATE_MOTOR_BACKWARD_PIN 5
#define GATE_CLOSED_END_PIN A6
#define GATE_OPENED_END_PIN A7

#define FEEDER_MOTOR_FORWARD_PIN 6
#define FEEDER_MOTOR_BACKWARD_PIN 3
#define FEEDER_CONSTRAIN_END_PIN 12
#define FEEDER_CONSTRAIN_IR_PIN A2

#define LOADING_DRUM_MOVER_MOTOR_FORWARD_PIN 8
#define LOADING_DRUM_MOVER_MOTOR_BACKWARD_PIN 7
#define LOADING_DRUM_MOVER_MOTOR_FRONT_END_PIN 4
#define LOADING_DRUM_MOVER_MOTOR_BACK_END_PIN 2

#define LOADING_DRUM_ROTATION_MOTOR_FORWARD_PIN 11
#define LOADING_DRUM_ROTATION_MOTOR_BACKWARD_PIN 10
#define LOADING_DRUM_ROTATION_MOTOR_POSITION_PIN A1
#define LOADING_DRUM_ROTATION_SHELL_CHECKER_PIN A0

#define IS_SHELL analogRead(LOADING_DRUM_ROTATION_SHELL_CHECKER_PIN) > 500

// Commands
#define RESET_STATUS_COMMAND 0x00
#define CALIBRATION_COMMAND 0x01
#define ACTIVATE_LOADER_DRUM 0x02
#define DEACTIVATE_LOADER_DRUM 0x03
#define LOAD_SHELL 0x04
#define COMMAND_FINISH_LOAD_SHELL 0x05
#define COMMAND_UNLOAD_SHELL 0x06
#define COMMAND_CLOCKWISE_DRUM_ROTATION 0x07
#define COMMAND_COUNTER_CLOCKWISE_DRUM_ROTATION 0x08
#define COMMAND_OPEN_DRUM_GATE 0x09
#define COMMAND_CLOSE_DRUM_GATE 0x0A
#define COMMAND_PUSH_FEEDER 0x0B
#define COMMAND_PULL_FEEDER 0x0C
#define COMMAND_FALSIFY_CALIBRATION 0x0D

// Error codes
#define NO_ERROR 0x0
#define ERROR_CALIBRATION_REQUIRED 0x1

#define ERROR_GATE_OPENING_TIMEOUT 0x2
#define ERROR_GATE_CLOSING_TIMEOUT 0x3

#define ERROR_LOADING_DRUM_ACTIVATION_TIMEOUT 0x4
#define ERROR_LOADING_DRUM_DEACTIVATION_TIMEOUT 0x5

#define ERROR_FEEDER_PUSH_TIMEOUT 0x6
#define ERROR_FEEDER_PULL_TIMEOUT 0x7

#define ERROR_DRUM_CLOCKWISE_ROTATION_TIMEOUT 0x8
#define ERROR_DRUM_COUNTER_CLOCKWISE_ROTATION_TIMEOUT 0x9

#define ERROR_NO_SHELLS_TO_LOAD 0xA
#define ERROR_NO_EMPTY_CELL_TO_UNLOAD_BREECHBLOCK 0xB
#define ERROR_COULD_NOT_PULL_SHELL_FROM_BREECHBLOCK 0xC

// Command Execution Status
#define CES_IDLE 0
#define CES_DOING 1
#define CES_DONE 2
#define CES_FAILED 3
// -------------------------

void init_pins(void) {
  pinMode(GATE_MOTOR_FORWARD_PIN, OUTPUT);
  pinMode(GATE_MOTOR_BACKWARD_PIN, OUTPUT);
  pinMode(GATE_CLOSED_END_PIN, INPUT);
  pinMode(GATE_OPENED_END_PIN, INPUT);
  pinMode(FEEDER_MOTOR_FORWARD_PIN, OUTPUT);
  pinMode(FEEDER_MOTOR_BACKWARD_PIN, OUTPUT);
  pinMode(FEEDER_CONSTRAIN_END_PIN, INPUT_PULLUP);
  pinMode(FEEDER_CONSTRAIN_IR_PIN, INPUT);
  pinMode(LOADING_DRUM_MOVER_MOTOR_FORWARD_PIN, OUTPUT);
  pinMode(LOADING_DRUM_MOVER_MOTOR_BACKWARD_PIN, OUTPUT);
  pinMode(LOADING_DRUM_MOVER_MOTOR_FRONT_END_PIN, INPUT_PULLUP);
  pinMode(LOADING_DRUM_MOVER_MOTOR_BACK_END_PIN, INPUT_PULLUP);
  pinMode(LOADING_DRUM_ROTATION_MOTOR_FORWARD_PIN, OUTPUT);
  pinMode(LOADING_DRUM_ROTATION_MOTOR_BACKWARD_PIN, OUTPUT);
  pinMode(LOADING_DRUM_ROTATION_MOTOR_POSITION_PIN, INPUT);
  pinMode(LOADING_DRUM_ROTATION_SHELL_CHECKER_PIN, INPUT);
}

#endif