#ifndef __CONFIG_H__
#define __CONFIG_H__

#define FIRE_RELAY_PIN 7
#define CONTACT_VALIDATOR_PIN 4
#define BREECH_BLOCK_GATE_MOTOR_CLOSING_PIN 9 
#define BREECH_BLOCK_GATE_MOTOR_OPENING_PIN 6
#define BREECH_BLOCK_GATE_IR_PIN 3
#define BREECH_BLOCK_GATE_CONSTRAIN_END_PIN 2
#define LASER_PIN 12
#define BAREL_LEFT_LIGHTS_PIN 11
#define BAREL_RIGHT_LIGHTS_PIN 10
#define BREECH_BLOCK_AND_LOADING_DRUM_CONNECTION_CHECKER_PIN 5

void init_pins() {
  pinMode(FIRE_RELAY_PIN, OUTPUT);
  pinMode(CONTACT_VALIDATOR_PIN, INPUT_PULLUP);
  pinMode(BREECH_BLOCK_GATE_MOTOR_CLOSING_PIN, OUTPUT);
  pinMode(BREECH_BLOCK_GATE_MOTOR_OPENING_PIN, OUTPUT);
  pinMode(BREECH_BLOCK_GATE_IR_PIN, INPUT);
  pinMode(BREECH_BLOCK_GATE_CONSTRAIN_END_PIN, INPUT_PULLUP);
  pinMode(LASER_PIN, OUTPUT);
  pinMode(BAREL_LEFT_LIGHTS_PIN, OUTPUT);
  pinMode(BAREL_RIGHT_LIGHTS_PIN, OUTPUT);
}

#endif