#ifndef __CONFIG_H__
#define __CONFIG_H__

#define CHIP_ENABLE_IN 49
#define  CHIP_SELECT_IN 48

unsigned char ENCRYPTION_KEY[16] = {1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16}; 

#define IS_SWITCH_ON(PIN) !digitalRead(PIN)

#define LIGHT_SWITCH_BACK 43
#define LIGHT_SWITCH_FRONT 44
#define LIGHT_SWITCH_LONG 45
#define LIGHT_SWITCH_TURRET 46

#define GUN_SWITCH 30
#define RELOADER_TAKE_BUTTON 31
#define RELOADER_LOAD_BUTTON 32
#define GUN_STABILIZER_SWITCH 33
#define FIRE_A_BUTTON 34

#define ARM_TURRET_JOY_X 0
#define ARM_TURRET_JOY_Y 1
#define ARM_TURRET_JOY_R 2

#define DRIVE_JOY_X 3
#define DRIVE_JOY_Y 4
#define DRIVE_JOY_R 5

#define FIRE_B_BUTTON 36
#define FOLLOW_TARGET_BUTTON 37
#define FOLLOW_TARGET_LED 38

#define DRIVING_SPEED_POTENTIOMETER 10
#define DRIVING_MODE_SWITCH 42
#define DRIVING_ERROR_LED 41

#define DISPLAY_LEFT_BUTTON 24
#define DISPLAY_OK_CANCEL_BUTTON 23
#define DISPLAY_LEFT_RIGHT 22

#define ARM_MODE_SWITCH 29
#define BATTLE_MODE_DOUBLE_SWITCH A13

#define AUTO_SHOOTING_SWITCH 12
#define FIRE_SWITCH 11
#define KEY_SWITCH 10
#define FIRE_CON_GREEN_LED 9
#define FIRE_CON_RED_LED 8

#define ARM_TURRET_SPEED_POTENTIOMETER A8
#define PROG_POTENTIOMETER A9
#define ARM_TURRET_ERROR_LED 40

#define LOADER_TAKE_GREEN_LED 4
#define LOADER_TAKE_RED_LED 5
#define LOADER_LOAD_GREEN_LED 6
#define LOADER_LOAD_RED_LED 7

#define CAMERA_JOY_X A6
#define CAMERA_JOY_Y A7
#define CAMERA_JOY_BUTTON 39

#define CAMERA_SWITCH A11
#define CAMERA_MOVEMENT_SPEED_POTENTIOMETER A12
#define LASER_SWITCH 35

#define DISPLAY_ADDRESS 0x3C

void init_pins() {
  pinMode(LIGHT_SWITCH_BACK, INPUT_PULLUP);
  pinMode(LIGHT_SWITCH_FRONT, INPUT_PULLUP);
  pinMode(LIGHT_SWITCH_LONG, INPUT_PULLUP);
  pinMode(LIGHT_SWITCH_TURRET, INPUT_PULLUP);

  pinMode(GUN_SWITCH, INPUT_PULLUP);
  pinMode(RELOADER_TAKE_BUTTON, INPUT_PULLUP);
  pinMode(RELOADER_LOAD_BUTTON, INPUT_PULLUP);
  pinMode(GUN_STABILIZER_SWITCH, INPUT_PULLUP);
  pinMode(FIRE_A_BUTTON, INPUT_PULLUP);

  pinMode(ARM_TURRET_JOY_X, INPUT);
  pinMode(ARM_TURRET_JOY_Y, INPUT);
  pinMode(ARM_TURRET_JOY_R, INPUT);

  pinMode(DRIVE_JOY_X, INPUT);
  pinMode(DRIVE_JOY_Y, INPUT);
  pinMode(DRIVE_JOY_R, INPUT);

  pinMode(FOLLOW_TARGET_BUTTON, INPUT_PULLUP);
  pinMode(FIRE_B_BUTTON, INPUT_PULLUP);
  pinMode(FOLLOW_TARGET_LED, OUTPUT);

  pinMode(DRIVING_SPEED_POTENTIOMETER, INPUT);
  pinMode(DRIVING_MODE_SWITCH, INPUT_PULLUP);
  pinMode(DRIVING_ERROR_LED, OUTPUT);

  pinMode(DISPLAY_LEFT_BUTTON, INPUT_PULLUP);
  pinMode(DISPLAY_OK_CANCEL_BUTTON, INPUT_PULLUP);
  pinMode(DISPLAY_LEFT_RIGHT, INPUT_PULLUP);

  pinMode(ARM_MODE_SWITCH, INPUT);
  pinMode(BATTLE_MODE_DOUBLE_SWITCH, INPUT);

  pinMode(AUTO_SHOOTING_SWITCH, INPUT_PULLUP);
  pinMode(FIRE_SWITCH, INPUT_PULLUP);
  pinMode(KEY_SWITCH, INPUT_PULLUP);
  pinMode(FIRE_CON_GREEN_LED, OUTPUT);
  pinMode(FIRE_CON_RED_LED, OUTPUT);

  pinMode(ARM_TURRET_SPEED_POTENTIOMETER, INPUT);
  pinMode(PROG_POTENTIOMETER, INPUT);
  pinMode(ARM_TURRET_ERROR_LED, OUTPUT);

  pinMode(LOADER_TAKE_GREEN_LED, OUTPUT);
  pinMode(LOADER_TAKE_RED_LED, OUTPUT);
  pinMode(LOADER_LOAD_GREEN_LED, OUTPUT);
  pinMode(LOADER_LOAD_RED_LED, OUTPUT);

  pinMode(CAMERA_JOY_X, INPUT);
  pinMode(CAMERA_JOY_Y, INPUT);
  pinMode(CAMERA_JOY_BUTTON, INPUT);

  pinMode(CAMERA_SWITCH, INPUT);
  pinMode(CAMERA_MOVEMENT_SPEED_POTENTIOMETER, INPUT);
  pinMode(LASER_SWITCH, INPUT_PULLUP);
}

#endif