#ifndef __CONFIG_H__
#define __CONFIG_H__

#define COMMANDER_CAMERA_HORIZONTAL_SERVO_PIN 5
#define COMMANDER_CAMERA_VERTICAL_SERVO_PIN 6
#define GUN_VERTICAL_SERVO_PIN 3
#define TURRET_ROTATION_DIR_PIN 2
#define TURRET_ROTATION_STEP_PIN 7
#define COMMANDER_CAMERA_LIGHTS_PIN 9
#define WARNING_LED_PIN 13
#define GUN_VERTICAL_CONSTRAIN_END_PIN 12
#define GUN_HORIZONTAL_CONSTRAIN_END_PIN A0

void init_pins(void) {
  pinMode(TURRET_ROTATION_DIR_PIN, OUTPUT);
  pinMode(TURRET_ROTATION_STEP_PIN, OUTPUT);
  pinMode(COMMANDER_CAMERA_LIGHTS_PIN, OUTPUT);
  pinMode(WARNING_LED_PIN, OUTPUT);
  pinMode(GUN_VERTICAL_CONSTRAIN_END_PIN, INPUT_PULLUP);
  pinMode(GUN_HORIZONTAL_CONSTRAIN_END_PIN, INPUT);
}

#endif