#ifndef __CONFIG_H__
#define __CONFIG_H__

#define COMMANDER_CAMERA_HORIZONTAL_SERVO_PIN 5
#define COMMANDER_CAMERA_VERTICAL_SERVO_PIN 6
#define GUN_VERTICAL_SERVO_PIN 3
#define TURRET_ROTATION_DIR_PIN 2
#define TURRET_ROTATION_STEP_PIN 7
#define TURRET_ROTATION_ENABLE_PIN 4
#define COMMANDER_CAMERA_LIGHTS_PIN 9
#define WARNING_LED_PIN 13
#define GUN_VERTICAL_CONSTRAIN_END_PIN 12
#define GUN_HORIZONTAL_CONSTRAIN_END_PIN A0

// Loader State
#define LS_REQUIRES_CALIBRATION 0
#define LS_CALIBRATION 1
#define LS_LOADING 2
#define LS_UNLOADING 3
#define LS_LOADED 4
#define LS_UNLOADED 5
#define LS_RELOADING 6
#define LS_FAILURE 7

// Commands
#define TASK_LOAD 0x02
#define TASK_UNLOAD 0x03
#define TASK_CALIBRATE 0x04
#define TASK_OPEN_LOADING_DRUM_GATE 0x05
#define TASK_CLOSE_LOADING_DRUM_GATE 0x06
#define TASK_CONNECT_LOADING_DRUM 0x07
#define TASK_DISCCONNECT_LOADING_DRUM 0x08
#define TASK_ROTATE_LOADING_DRUM_CLOCKWISE 0x09
#define TASK_ROTATE_LOADING_DRUM_COUNTER_CLOCKWISE 0x0A
#define TASK_PUSH_FEEDER_LOADING_DRUM 0x0B
#define TASK_PULL_FEEDER_LOADING_DRUM 0x0C
#define TASK_OPEN_BREECHBLOCK_GATE 0x0D
#define TASK_CLOSE_BREECHBLOCK_GATE 0x0E
#define TASK_PRE_CLOSE_BREECHBLOCK_GATE 0x0F
#define TASK_RELOAD 0x10
#define TASK_FALCIFY_CALIBRATION 0x11
#define TASK_MAKE_SHOT 0x12

#define ERROR_NO_SHELL_CONNECTION 0x3

void init_pins(void) {
  pinMode(TURRET_ROTATION_DIR_PIN, OUTPUT);
  pinMode(TURRET_ROTATION_STEP_PIN, OUTPUT);
  pinMode(COMMANDER_CAMERA_LIGHTS_PIN, OUTPUT);
  pinMode(WARNING_LED_PIN, OUTPUT);
  pinMode(GUN_VERTICAL_CONSTRAIN_END_PIN, INPUT_PULLUP);
  pinMode(GUN_HORIZONTAL_CONSTRAIN_END_PIN, INPUT);
  pinMode(TURRET_ROTATION_ENABLE_PIN, OUTPUT);
}

#endif