name: tank-ci
on: workflow_dispatch
# on:
#   push:
#     branches:
#     - main

jobs:
  compile_modules:
    name: Compiles all modules
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: ls
        run: ls
      - name: "Install Arduino CLI" 
        run: curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
