name: tank-ci
on: workflow_dispatch
# on:
#   push:
#     branches:
#     - main
env:
  OSD_TARGET_BOARD: arduino:avr:nano
  TANK_TARGET_BOARD: arduino:avr:mega
  ARDUINO_CLI_LIBRARIES_DIR: /home/runner/Arduino

jobs:
  compile_modules:
    name: Compiles all modules
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: "Install Arduino CLI" 
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=/usr/local/bin sh
          arduino-cli core install arduino:avr
          
      - name: Install Libraries
        run: | 
          arduino-cli lib install RadioHead
          sed -i 's!//#define RH_ENABLE_ENCRYPTION_MODULE!#define RH_ENABLE_ENCRYPTION_MODULE!' $ARDUINO_CLI_LIBRARIES_DIR/RadioHead/RadioHead.h
          cat $ARDUINO_CLI_LIBRARIES_DIR/RadioHead/RadioHead.h
        
      - name: Compiler platform/OSD module
        run: arduino-cli compile -b $OSD_TARGET_BOARD -e ./platform/osd

      - name: Compiler platform/receiver
        run: arduino-cli compile -b $TANK_TARGET_BOARD -e ./platform/receiver
