name: tank-ci
on: workflow_dispatch
# on:
#   push:
#     branches:
#     - main
env:
  OSD_TARGET_BOARD: arduino:avr:nano

jobs:
  compile_modules:
    name: Compiles all modules
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: "Install Arduino CLI" 
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=/usr/local/bin sh
          arduino-cli core install arduino:avr
          
      - name: Compiler platform/OSD module
        run: arduino-cli compile -b $OSD_TARGET_BOARD -e ./platform/osd
